apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-05-14T14:59:14Z"
    generation: 1
    labels:
      app: auth0crud
    name: auth0crud
    namespace: default
    resourceVersion: "502"
    uid: 7392fe98-5a34-484c-9929-f3bd70aaa184
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: auth0crud
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: auth0crud
      spec:
        containers:
        - image: amith0504/auth0repo:11
          imagePullPolicy: IfNotPresent
          name: auth0repo
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-05-14T14:59:38Z"
      lastUpdateTime: "2024-05-14T14:59:38Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-05-14T14:59:14Z"
      lastUpdateTime: "2024-05-14T14:59:38Z"
      message: ReplicaSet "auth0crud-68c5dc65bf" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
