apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-05-14T14:59:14Z"
    generateName: auth0crud-68c5dc65bf-
    labels:
      app: auth0crud
      pod-template-hash: 68c5dc65bf
    name: auth0crud-68c5dc65bf-9499n
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: auth0crud-68c5dc65bf
      uid: b2f872d3-e7a0-47b3-a342-08311f67bcbb
    resourceVersion: "500"
    uid: 49667a05-a86b-4a59-8c79-c8044c703dd3
  spec:
    containers:
    - image: amith0504/auth0repo:11
      imagePullPolicy: IfNotPresent
      name: auth0repo
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-spkjw
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: minikube
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-spkjw
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-05-14T14:59:38Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2024-05-14T14:59:14Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-05-14T14:59:38Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-05-14T14:59:38Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-05-14T14:59:14Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://14cfe56bbde0a69b1f9338132ac3ff66f8047070de4c20e3804c4f72e628315f
      image: amith0504/auth0repo:11
      imageID: docker-pullable://amith0504/auth0repo@sha256:772226070271a9008357738ec5d7be7289aaf4f2ce7b9451b872c8ea853f4a80
      lastState: {}
      name: auth0repo
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-05-14T14:59:38Z"
    hostIP: 192.168.49.2
    hostIPs:
    - ip: 192.168.49.2
    phase: Running
    podIP: 10.244.0.3
    podIPs:
    - ip: 10.244.0.3
    qosClass: BestEffort
    startTime: "2024-05-14T14:59:14Z"
kind: List
metadata:
  resourceVersion: ""
